name: feature-pipeline
on: [push]
permissions:
  contents: read
  statuses: write
jobs: 
   # testing with new-feature branch
  feature-pipeline:
    if: github.ref != 'refs/head/main' # if not main branch. it works
    uses: Shankar-t-Codes/reuseable-workflows/.github/workflows/featured-node-js-pipeline.yaml@main
    with:
      project: ellamma-ecommerce
      component: catalogue
      environment: dev
    secrets: inherit

    # added condition
    feature-pipeline:
    if: github.ref == 'refs/head/main' # if main branch. it works
    uses: Shankar-t-Codes/reuseable-workflows/.github/workflows/dev-node-js-pipeline.yaml@main
    with:
      project: ellamma-ecommerce
      component: catalogue
      environment: dev
    secrets: inherit

